- hosts: localhost
  connection: local
  gather_facts: yes
  tasks:
  - name: clone repository
    git:
      repo: https://github.com/eslamsadawi/mydepiproject.git
      dest: /opt/docker/depi-shop
      clone: yes
      update: yes

  - name: create docker image
    command: docker build -t depi-shop:latest /opt/docker/depi-shop
    args:
      chdir: /opt/docker/depi-shop
  # - name: log in to Docker Hub
  #   command: docker login -u omarabdelwahab1 -p omarahmed.81204 # Temporarily removing no_log to see errors

  # - name: push Docker image to Docker Hub
  #   command: docker push omarabdelwahab1/cafe-app:latest
