- hosts: localhost
  connection: local
  gather_facts: yes
  tasks:
    - name: Check Kubernetes connectivity
      command: kubectl cluster-info
      register: cluster_info
      ignore_errors: yes
      
    - name: Display cluster info if successful
      debug:
        msg: "{{ cluster_info.stdout_lines }}"
      when: cluster_info.rc == 0
      
    - name: Display error message if connectivity fails
      debug:
        msg: "Failed to connect to Kubernetes cluster. Check connectivity and cluster status."
      when: cluster_info.rc != 0

    - name: deploy cafeapp on kubernetes
      command: kubectl apply -f cafe-app-deployment.yml --validate=false
      args:
        chdir: ../K8S
      register: deployment_result
      ignore_errors: yes

    - name: Debug deployment result
      debug:
        var: deployment_result
      
    - name: create service for cafeapp
      command: kubectl apply -f cafe-app-svc.yml --validate=false
      args:
        chdir: ../K8S
      register: service_result
      ignore_errors: yes

    - name: Debug service result
      debug:
        var: service_result

    - name: Update deployment with new pods if image updated in docker hub
      command: kubectl rollout restart deployment.apps/mylab1-cafe-app
      ignore_errors: yes
      when: deployment_result.rc == 0

